//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LearnMVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class AppDataConnectionEntity : DbContext
    {
        public AppDataConnectionEntity()
            : base("name=AppDataConnectionEntity")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Postal_Delivery_Type> Postal_Delivery_Type { get; set; }
        public virtual DbSet<Postal_Division_List> Postal_Division_List { get; set; }
        public virtual DbSet<Postal_Office_List> Postal_Office_List { get; set; }
        public virtual DbSet<Postal_Office_Type> Postal_Office_Type { get; set; }
        public virtual DbSet<Postal_Pincode_List> Postal_Pincode_List { get; set; }
        public virtual DbSet<Postal_Region_List> Postal_Region_List { get; set; }
        public virtual DbSet<Postal_State_List> Postal_State_List { get; set; }
        public virtual DbSet<UploadTransactionLog> UploadTransactionLogs { get; set; }
        public virtual DbSet<UploadTranSummary> UploadTranSummaries { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Login_Credentials> Login_Credentials { get; set; }
        public virtual DbSet<Data_Process_Log> Data_Process_Log { get; set; }
        public virtual DbSet<ASCII_Reference> ASCII_Reference { get; set; }
        public virtual DbSet<AutoGeneratedAudit> AutoGeneratedAudits { get; set; }
        public virtual DbSet<AutoGeneratedDate> AutoGeneratedDates { get; set; }
        public virtual DbSet<AutoGeneratedName> AutoGeneratedNames { get; set; }
        public virtual DbSet<ConsigneeDetail> ConsigneeDetails { get; set; }
        public virtual DbSet<ConsignmentDetail> ConsignmentDetails { get; set; }
        public virtual DbSet<LoanDetail> LoanDetails { get; set; }
        public virtual DbSet<NumToWord> NumToWords { get; set; }
        public virtual DbSet<Postal_Circle_List> Postal_Circle_List { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TransactionSummary> TransactionSummaries { get; set; }
        public virtual DbSet<Covid_TestData> Covid_TestData { get; set; }
        public virtual DbSet<EmiTable> EmiTables { get; set; }
        public virtual DbSet<Postal_District_List> Postal_District_List { get; set; }
        public virtual DbSet<Menu> Menus { get; set; }
        public virtual DbSet<Announcement> Announcements { get; set; }
        public virtual DbSet<LandingImage> LandingImages { get; set; }
    
        public virtual int Record_Upload_Transaction_Log(string uploadServerTranID, string uploadfilename, string filepath, string descr, string createdby, Nullable<System.DateTime> createddate)
        {
            var uploadServerTranIDParameter = uploadServerTranID != null ?
                new ObjectParameter("UploadServerTranID", uploadServerTranID) :
                new ObjectParameter("UploadServerTranID", typeof(string));
    
            var uploadfilenameParameter = uploadfilename != null ?
                new ObjectParameter("uploadfilename", uploadfilename) :
                new ObjectParameter("uploadfilename", typeof(string));
    
            var filepathParameter = filepath != null ?
                new ObjectParameter("filepath", filepath) :
                new ObjectParameter("filepath", typeof(string));
    
            var descrParameter = descr != null ?
                new ObjectParameter("descr", descr) :
                new ObjectParameter("descr", typeof(string));
    
            var createdbyParameter = createdby != null ?
                new ObjectParameter("createdby", createdby) :
                new ObjectParameter("createdby", typeof(string));
    
            var createddateParameter = createddate.HasValue ?
                new ObjectParameter("createddate", createddate) :
                new ObjectParameter("createddate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Record_Upload_Transaction_Log", uploadServerTranIDParameter, uploadfilenameParameter, filepathParameter, descrParameter, createdbyParameter, createddateParameter);
        }
    
        public virtual int Insert_User_Details(string first_name, string last_name, string gender, string phone, string email, string username, string password)
        {
            var first_nameParameter = first_name != null ?
                new ObjectParameter("first_name", first_name) :
                new ObjectParameter("first_name", typeof(string));
    
            var last_nameParameter = last_name != null ?
                new ObjectParameter("last_name", last_name) :
                new ObjectParameter("last_name", typeof(string));
    
            var genderParameter = gender != null ?
                new ObjectParameter("gender", gender) :
                new ObjectParameter("gender", typeof(string));
    
            var phoneParameter = phone != null ?
                new ObjectParameter("phone", phone) :
                new ObjectParameter("phone", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Insert_User_Details", first_nameParameter, last_nameParameter, genderParameter, phoneParameter, emailParameter, usernameParameter, passwordParameter);
        }
    
        public virtual int Update_User_Details(string userID, string first_name, string last_name, string gender, string email, string phone)
        {
            var userIDParameter = userID != null ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(string));
    
            var first_nameParameter = first_name != null ?
                new ObjectParameter("first_name", first_name) :
                new ObjectParameter("first_name", typeof(string));
    
            var last_nameParameter = last_name != null ?
                new ObjectParameter("last_name", last_name) :
                new ObjectParameter("last_name", typeof(string));
    
            var genderParameter = gender != null ?
                new ObjectParameter("gender", gender) :
                new ObjectParameter("gender", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var phoneParameter = phone != null ?
                new ObjectParameter("phone", phone) :
                new ObjectParameter("phone", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Update_User_Details", userIDParameter, first_nameParameter, last_nameParameter, genderParameter, emailParameter, phoneParameter);
        }
    
        public virtual int Get_User_Details_By_UserID(string userid)
        {
            var useridParameter = userid != null ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Get_User_Details_By_UserID", useridParameter);
        }
    
        public virtual int Generate_Upload_Transaction_Summary(string stageTransactionID, string reportType)
        {
            var stageTransactionIDParameter = stageTransactionID != null ?
                new ObjectParameter("StageTransactionID", stageTransactionID) :
                new ObjectParameter("StageTransactionID", typeof(string));
    
            var reportTypeParameter = reportType != null ?
                new ObjectParameter("ReportType", reportType) :
                new ObjectParameter("ReportType", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Generate_Upload_Transaction_Summary", stageTransactionIDParameter, reportTypeParameter);
        }
    
        public virtual ObjectResult<User_Login_Auth_Result> User_Login_Auth(string userid, string pwd)
        {
            var useridParameter = userid != null ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(string));
    
            var pwdParameter = pwd != null ?
                new ObjectParameter("pwd", pwd) :
                new ObjectParameter("pwd", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<User_Login_Auth_Result>("User_Login_Auth", useridParameter, pwdParameter);
        }
    
        public virtual int User_Auth(string userid, string pwd)
        {
            var useridParameter = userid != null ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(string));
    
            var pwdParameter = pwd != null ?
                new ObjectParameter("pwd", pwd) :
                new ObjectParameter("pwd", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("User_Auth", useridParameter, pwdParameter);
        }
    
        public virtual int Search_Get_User_List(string userID)
        {
            var userIDParameter = userID != null ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Search_Get_User_List", userIDParameter);
        }
    
        public virtual ObjectResult<User> All_User_List(string userID)
        {
            var userIDParameter = userID != null ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<User>("All_User_List", userIDParameter);
        }
    
        public virtual ObjectResult<User> All_User_List(string userID, MergeOption mergeOption)
        {
            var userIDParameter = userID != null ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<User>("All_User_List", mergeOption, userIDParameter);
        }
    
        public virtual int GetCircleNameDDL(string stateID)
        {
            var stateIDParameter = stateID != null ?
                new ObjectParameter("StateID", stateID) :
                new ObjectParameter("StateID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetCircleNameDDL", stateIDParameter);
        }
    
        public virtual int GetDivisionNamDDL(string regionID)
        {
            var regionIDParameter = regionID != null ?
                new ObjectParameter("RegionID", regionID) :
                new ObjectParameter("RegionID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetDivisionNamDDL", regionIDParameter);
        }
    
        public virtual int GetRegionNameDDL(string circleID)
        {
            var circleIDParameter = circleID != null ?
                new ObjectParameter("CircleID", circleID) :
                new ObjectParameter("CircleID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetRegionNameDDL", circleIDParameter);
        }
    
        public virtual int GetDistrictNameDDL(string divisionID)
        {
            var divisionIDParameter = divisionID != null ?
                new ObjectParameter("DivisionID", divisionID) :
                new ObjectParameter("DivisionID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetDistrictNameDDL", divisionIDParameter);
        }
    
        public virtual int GetOfficeNameDDL(string districtID)
        {
            var districtIDParameter = districtID != null ?
                new ObjectParameter("DistrictID", districtID) :
                new ObjectParameter("DistrictID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetOfficeNameDDL", districtIDParameter);
        }
    
        public virtual ObjectResult<Get_OfficeDetails_By_Pincode_Result> Get_OfficeDetails_By_Pincode(Nullable<int> pincode)
        {
            var pincodeParameter = pincode.HasValue ?
                new ObjectParameter("pincode", pincode) :
                new ObjectParameter("pincode", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_OfficeDetails_By_Pincode_Result>("Get_OfficeDetails_By_Pincode", pincodeParameter);
        }
    
        public virtual ObjectResult<GetHomePageMenu_Result> GetHomePageMenu()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetHomePageMenu_Result>("GetHomePageMenu");
        }
    
        public virtual int UpdateConsignmentStatus(string bookingID, string status)
        {
            var bookingIDParameter = bookingID != null ?
                new ObjectParameter("BookingID", bookingID) :
                new ObjectParameter("BookingID", typeof(string));
    
            var statusParameter = status != null ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateConsignmentStatus", bookingIDParameter, statusParameter);
        }
    
        public virtual ObjectResult<string> UpdateConsignmentStatus1(string bookingID, string status)
        {
            var bookingIDParameter = bookingID != null ?
                new ObjectParameter("BookingID", bookingID) :
                new ObjectParameter("BookingID", typeof(string));
    
            var statusParameter = status != null ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UpdateConsignmentStatus1", bookingIDParameter, statusParameter);
        }
    
        public virtual ObjectResult<string> InsertAnnouncements(string announcementTitle, string announcementContent, string createdBy, string classification)
        {
            var announcementTitleParameter = announcementTitle != null ?
                new ObjectParameter("AnnouncementTitle", announcementTitle) :
                new ObjectParameter("AnnouncementTitle", typeof(string));
    
            var announcementContentParameter = announcementContent != null ?
                new ObjectParameter("AnnouncementContent", announcementContent) :
                new ObjectParameter("AnnouncementContent", typeof(string));
    
            var createdByParameter = createdBy != null ?
                new ObjectParameter("createdBy", createdBy) :
                new ObjectParameter("createdBy", typeof(string));
    
            var classificationParameter = classification != null ?
                new ObjectParameter("classification", classification) :
                new ObjectParameter("classification", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("InsertAnnouncements", announcementTitleParameter, announcementContentParameter, createdByParameter, classificationParameter);
        }
    
        public virtual int InsertLandingPageImages(string landingimagename, string landingImagePath, Nullable<int> sortOrder, string createdby)
        {
            var landingimagenameParameter = landingimagename != null ?
                new ObjectParameter("landingimagename", landingimagename) :
                new ObjectParameter("landingimagename", typeof(string));
    
            var landingImagePathParameter = landingImagePath != null ?
                new ObjectParameter("LandingImagePath", landingImagePath) :
                new ObjectParameter("LandingImagePath", typeof(string));
    
            var sortOrderParameter = sortOrder.HasValue ?
                new ObjectParameter("SortOrder", sortOrder) :
                new ObjectParameter("SortOrder", typeof(int));
    
            var createdbyParameter = createdby != null ?
                new ObjectParameter("Createdby", createdby) :
                new ObjectParameter("Createdby", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertLandingPageImages", landingimagenameParameter, landingImagePathParameter, sortOrderParameter, createdbyParameter);
        }
    
        public virtual ObjectResult<Get_User_List_Result> Get_User_List(string userID)
        {
            var userIDParameter = userID != null ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_User_List_Result>("Get_User_List", userIDParameter);
        }
    
        public virtual ObjectResult<GetAnnouncements_Result1> GetAnnouncements(string userid, Nullable<System.DateTime> from, Nullable<System.DateTime> to, string announcementClassification)
        {
            var useridParameter = userid != null ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(string));
    
            var fromParameter = from.HasValue ?
                new ObjectParameter("from", from) :
                new ObjectParameter("from", typeof(System.DateTime));
    
            var toParameter = to.HasValue ?
                new ObjectParameter("to", to) :
                new ObjectParameter("to", typeof(System.DateTime));
    
            var announcementClassificationParameter = announcementClassification != null ?
                new ObjectParameter("AnnouncementClassification", announcementClassification) :
                new ObjectParameter("AnnouncementClassification", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAnnouncements_Result1>("GetAnnouncements", useridParameter, fromParameter, toParameter, announcementClassificationParameter);
        }
    
        public virtual ObjectResult<string> Create_Consignment_Booking(string consigneename, string consignername, string consigneeaddress, string consigneraddress, string tostateid, string circleid, string regionid, string divisionid, string districtid, string officeid, string officetypeid, string deliverytypeid, Nullable<int> destinationpincode, string createdby)
        {
            var consigneenameParameter = consigneename != null ?
                new ObjectParameter("consigneename", consigneename) :
                new ObjectParameter("consigneename", typeof(string));
    
            var consignernameParameter = consignername != null ?
                new ObjectParameter("consignername", consignername) :
                new ObjectParameter("consignername", typeof(string));
    
            var consigneeaddressParameter = consigneeaddress != null ?
                new ObjectParameter("consigneeaddress", consigneeaddress) :
                new ObjectParameter("consigneeaddress", typeof(string));
    
            var consigneraddressParameter = consigneraddress != null ?
                new ObjectParameter("consigneraddress", consigneraddress) :
                new ObjectParameter("consigneraddress", typeof(string));
    
            var tostateidParameter = tostateid != null ?
                new ObjectParameter("tostateid", tostateid) :
                new ObjectParameter("tostateid", typeof(string));
    
            var circleidParameter = circleid != null ?
                new ObjectParameter("circleid", circleid) :
                new ObjectParameter("circleid", typeof(string));
    
            var regionidParameter = regionid != null ?
                new ObjectParameter("regionid", regionid) :
                new ObjectParameter("regionid", typeof(string));
    
            var divisionidParameter = divisionid != null ?
                new ObjectParameter("divisionid", divisionid) :
                new ObjectParameter("divisionid", typeof(string));
    
            var districtidParameter = districtid != null ?
                new ObjectParameter("districtid", districtid) :
                new ObjectParameter("districtid", typeof(string));
    
            var officeidParameter = officeid != null ?
                new ObjectParameter("officeid", officeid) :
                new ObjectParameter("officeid", typeof(string));
    
            var officetypeidParameter = officetypeid != null ?
                new ObjectParameter("officetypeid", officetypeid) :
                new ObjectParameter("officetypeid", typeof(string));
    
            var deliverytypeidParameter = deliverytypeid != null ?
                new ObjectParameter("deliverytypeid", deliverytypeid) :
                new ObjectParameter("deliverytypeid", typeof(string));
    
            var destinationpincodeParameter = destinationpincode.HasValue ?
                new ObjectParameter("destinationpincode", destinationpincode) :
                new ObjectParameter("destinationpincode", typeof(int));
    
            var createdbyParameter = createdby != null ?
                new ObjectParameter("createdby", createdby) :
                new ObjectParameter("createdby", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("Create_Consignment_Booking", consigneenameParameter, consignernameParameter, consigneeaddressParameter, consigneraddressParameter, tostateidParameter, circleidParameter, regionidParameter, divisionidParameter, districtidParameter, officeidParameter, officetypeidParameter, deliverytypeidParameter, destinationpincodeParameter, createdbyParameter);
        }
    
        public virtual ObjectResult<Get_Consignment_Details_By_BookingID1_Result> Get_Consignment_Details_By_BookingID(string bookingID)
        {
            var bookingIDParameter = bookingID != null ?
                new ObjectParameter("BookingID", bookingID) :
                new ObjectParameter("BookingID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_Consignment_Details_By_BookingID1_Result>("Get_Consignment_Details_By_BookingID", bookingIDParameter);
        }
    }
}
