//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LearnMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASCII_Reference
    {
        public string ASCII_Ref_ID { get; set; }
        public Nullable<int> ASCII_Code { get; set; }
        public Nullable<int> Unicode_Code { get; set; }
        public string Ref_Char { get; set; }
        public Nullable<int> Ref_Int { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifedBy { get; set; }
        public Nullable<System.DateTime> ModifedDate { get; set; }
    }
}
