//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LearnMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AutoGeneratedAudit
    {
        public string AGDID { get; set; }
        public string AutoGenRefID { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string GeneratedBy { get; set; }
        public Nullable<System.DateTime> GeneratedDate { get; set; }
        public string AutoGenType { get; set; }
        public Nullable<int> ProcessedRecords { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
