//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LearnMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AutoGeneratedDate
    {
        public string DateID { get; set; }
        public Nullable<int> Date { get; set; }
        public string Month { get; set; }
        public string Year { get; set; }
        public string Day { get; set; }
        public Nullable<System.DateTime> FullDate { get; set; }
        public Nullable<int> WeekNo { get; set; }
        public Nullable<bool> Active { get; set; }
        public string GeneratedBy { get; set; }
        public Nullable<System.DateTime> GeneratedDate { get; set; }
        public string AuditRefID { get; set; }
        public Nullable<bool> PublicHoliday { get; set; }
        public Nullable<bool> Weekend { get; set; }
        public Nullable<bool> SalaryProcessing { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
