//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LearnMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsigneeDetail
    {
        public string ConsigneeDetailsID { get; set; }
        public string BookingID { get; set; }
        public string ConsigneeName { get; set; }
        public string ConsignerName { get; set; }
        public string Active { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual ConsignmentDetail ConsignmentDetail { get; set; }
    }
}
