//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LearnMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Covid_TestData
    {
        public string Direction { get; set; }
        public short Year { get; set; }
        public System.DateTime Date { get; set; }
        public string Weekday { get; set; }
        public System.DateTime Current_Match { get; set; }
        public string Country { get; set; }
        public string Commodity { get; set; }
        public string Transport_Mode { get; set; }
        public string Measure { get; set; }
        public int Value { get; set; }
        public double Cumulative { get; set; }
    }
}
