//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LearnMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Data_Process_Log
    {
        public string DataProcessTranID { get; set; }
        public string ServerTransactionID { get; set; }
        public string UploadTransactionID { get; set; }
        public string UploadFileName { get; set; }
        public Nullable<System.DateTime> ProcessStart { get; set; }
        public Nullable<System.DateTime> ProcessEnd { get; set; }
        public string ProcessStatus { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
