//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LearnMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmiTable
    {
        public string EmiRefID { get; set; }
        public string LoanRefID { get; set; }
        public string LoanID { get; set; }
        public string Month { get; set; }
        public Nullable<System.DateTime> CycleDate { get; set; }
        public Nullable<System.DateTime> RepaymentDate { get; set; }
        public Nullable<int> PrincipleAmount { get; set; }
        public Nullable<int> InterestAmount { get; set; }
        public Nullable<int> TotalPayable { get; set; }
        public Nullable<bool> Paid { get; set; }
        public Nullable<bool> Active { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreateadDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual LoanDetail LoanDetail { get; set; }
    }
}
