//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LearnMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LoanDetail()
        {
            this.EmiTables = new HashSet<EmiTable>();
        }
    
        public string LoanRefID { get; set; }
        public string UserID { get; set; }
        public string LoanID { get; set; }
        public Nullable<decimal> PrincipleAmount { get; set; }
        public string Type { get; set; }
        public Nullable<decimal> Interest { get; set; }
        public Nullable<int> Tenure { get; set; }
        public Nullable<bool> Active { get; set; }
        public string Status { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<decimal> InterestPercent { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public Nullable<decimal> BalancePayable { get; set; }
        public Nullable<decimal> BalPrinciple { get; set; }
        public Nullable<decimal> BalInterest { get; set; }
        public Nullable<decimal> ProcessingAmt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmiTable> EmiTables { get; set; }
        public virtual User User { get; set; }
    }
}
