//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LearnMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public string MessageID { get; set; }
        public string SenderID { get; set; }
        public string ReceiverID { get; set; }
        public string MessageSubject { get; set; }
        public string Message1 { get; set; }
        public Nullable<bool> ReplyRequired { get; set; }
        public Nullable<bool> Acknowledged { get; set; }
        public string MessageParentID { get; set; }
        public string ReplyMessage { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public string ModifiedDate { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.DateTime> ReplyDate { get; set; }
    }
}
