//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LearnMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NumToWord
    {
        public int NumToWordsID { get; set; }
        public Nullable<int> IntValue { get; set; }
        public string WordValue { get; set; }
        public string Placeterm { get; set; }
        public Nullable<int> PlaceIntstart { get; set; }
        public Nullable<bool> Active { get; set; }
        public string CallbyTerm { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
