//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LearnMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeZone
    {
        public string TimezoneID { get; set; }
        public string Country { get; set; }
        public string Timezone1 { get; set; }
        public Nullable<int> AdjustHours { get; set; }
        public Nullable<int> AdjustMinutes { get; set; }
        public Nullable<System.DateTime> CountryTime { get; set; }
        public Nullable<int> Sortorder { get; set; }
        public Nullable<bool> Active { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> Highlight { get; set; }
    }
}
