//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LearnMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrackConsignment
    {
        public string TrackConsignmentID { get; set; }
        public string BookingID { get; set; }
        public string ConsignmentStatusID { get; set; }
        public System.DateTime StatusDateTime { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> SortOrder { get; set; }
    }
}
