//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LearnMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionSummary
    {
        public string TranSumryID { get; set; }
        public string AuditRefID { get; set; }
        public string ActionOn { get; set; }
        public string Action { get; set; }
        public string ActionStatus { get; set; }
        public string GeneratedBy { get; set; }
        public Nullable<System.DateTime> GeneratedDate { get; set; }
    
        public virtual TransactionSummary TransactionSummary1 { get; set; }
        public virtual TransactionSummary TransactionSummary2 { get; set; }
    }
}
