//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LearnMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UploadTranSummary
    {
        public string SummaryRefID { get; set; }
        public string StageTranID { get; set; }
        public string Description { get; set; }
        public Nullable<int> CountOfChanges { get; set; }
        public string Uploadedby { get; set; }
        public Nullable<System.DateTime> UploadedOn { get; set; }
    }
}
