//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LearnMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UploadTransactionLog
    {
        public string UploadTransactionID { get; set; }
        public string UploadFileName { get; set; }
        public string UploadFileServerPath { get; set; }
        public string UploadFileDescription { get; set; }
        public string UploadedBy { get; set; }
        public Nullable<System.DateTime> UploadedOn { get; set; }
        public string ServerTransactionID { get; set; }
    }
}
